import bg1 from "../assets/bg_img/background.jfif";
import bg2 from "../assets/bg_img/1.jpg";
import bg3 from "../assets/bg_img/2.jpg";
import bg4 from "../assets/bg_img/3.jpg";
import bg5 from "../assets/bg_img/4.jpg";
import bg6 from "../assets/bg_img/5.jpg";
import bg7 from "../assets/bg_img/6.jpg";
import bg8 from "../assets/bg_img/7.jpg";
import bg9 from "../assets/bg_img/8.jpg";
import bg10 from "../assets/bg_img/9.jpg";
import bg11 from "../assets/bg_img/10.jpg";
export default [bg1, bg2, bg3, bg4, bg5, bg6, bg7, bg8, bg9, bg10, bg11];
